/** تسميات حقول الرفع لإنفاذ — موحّدة بين شاشات الأدوار وتبويب الرفع. */
export const INFATH_FIELD_LABELS = {
  inspectionDate: "تاريخ المعاينة",
  appraisalDate: "تاريخ التقييم",
  valuationMethod: "الأسلوب المستخدم",
  appraiserAddress: "عنوان المقيم",
  appraiserPhone: "رقم تواصل المقيّم",
  reportIssueDate: "تاريخ إصدار التقرير",
  reportNumber: "رقم التقرير",
  valueBasis: "أساس القيمة",
  assetSubject: "الأصل محل التقييم",
  facade: "الواجهة",
  streetWidth: "عرض الشارع (م)",
  builtArea: "مساحة البناء (م²)",
  propertyUsage: "استخدام العقار",
  streetName: "اسم الشارع",
  zoneStatus: "حالة منطقة العقار",
  mainStreet: "اسم أقرب شارع رئيسي",
  mapCoords: "الموقع على الخارطة (إحداثيات)",
  roomCount: "عدد الغرف",
  hallCount: "عدد الصالات",
  unitCount: "عدد الشقق",
  bathroomCount: "عدد دورات المياه",
  propertyAge: "عمر العقار (سنة)",
  showroomCount: "عدد المعارض",
  towerCount: "عدد الأبراج",
  wellCount: "عدد الآبار",
  kitchen: "مطبخ",
  carEntrance: "مدخل السيارة",
  hasBasement: "يوجد قبو",
  hasElevator: "يوجد مصعد",
  hasPool: "يوجد مسبح",
  buildState: "حالة البناء",
  occupancyState: "حالة الإشغال",
  districtState: "حالة الحي",
  movables: "يوجد منقولات",
  demandLevel: "حجم الطلب على العقار",
  services: "الخدمات المتوفرة",
  amenities: "المرافق المحيطة",
  propertyDescription: "وصف العقار",
  districtProsCons: "الإيجابيات والعيوب الظاهرة على الحي",
  accessRoute: "طريقة الوصول للعقار",
  assetNotes: "ملاحظات على الأصل",
  northBoundary: "الحد الشمالي",
  northLength: "طول الحد الشمالي التقريبي (م)",
  southBoundary: "الحد الجنوبي",
  southLength: "طول الحد الجنوبي التقريبي (م)",
  eastBoundary: "الحد الشرقي",
  eastLength: "طول الحد الشرقي التقريبي (م)",
  westBoundary: "الحد الغربي",
  westLength: "طول الحد الغربي التقريبي (م)",
  buildingFloors: "عدد أدوار المباني",
  basementTotal: "إجمالي مساحة القبو (م²)",
  annexTotal: "إجمالي مساحة اللاحق (م²)",
  buildingsTotal: "إجمالي مساحة المباني (م²)",
  linkedAssets: "هل الأصل مرتبط بأصول أخرى؟",
  linkedDeedNumbers: "أرقام صكوك الأصول المرتبطة",
  linkedAssetsNotes: "ملاحظات ربط الأصل",
  landValue: "قيمة الأرض (ر.س)",
  buildingValue: "قيمة المباني (ر.س)",
  totalValue: "إجمالي قيمة العقار (ر.س)",
  forcedDiscount: "نسبة خصم البيع القسري",
  forcedSaleValue: "قيمة البيع القسري (ر.س)",
  siteLocation: "موقع الأصل",
  exteriorPhotos: "صور الأصل من الخارج (PDF مجمّع)",
  interiorPhotos: "صور الأصل من الداخل (PDF مجمّع)",
  planPhoto: "صورة الأصل من المخطط (PDF)",
  deedPhoto: "صك ملكية الأصل (PDF)",
  searchScope: "نطاق البحث ومصادر معلومات القيم",
  keysReceived: "هل تم استلام المفتاح من الدائرة؟",
  keysProof: "إثبات استلام المفتاح (خطاب أو صورة)",
  otherNotes: "ملاحظات",
  closingNotes: "ملاحظات ختامية",
  signedAppraisal: "مرفق التقييم المعتمد",
  onSiteArea: "المساحة على الطبيعة (م²)",
  deedAreaRef: "المساحة حسب الصك (م²)",
  areaDiff: "يوجد اختلاف في المساحة",
  surveyFile: "مرفق الرفع المساحي",
  surveyNotes: "ملاحظات الرفع المساحي",
} as const;

export const INFATH_YES_NO_OPTIONS = [
  { value: "yes", label: "نعم" },
  { value: "no", label: "لا" },
] as const;

export type InfathYesNo = (typeof INFATH_YES_NO_OPTIONS)[number]["value"] | "";

export function infathYesNoLabel(value: InfathYesNo | boolean | null): string {
  if (value === true || value === "yes") return "نعم";
  if (value === false || value === "no") return "لا";
  return "";
}
