/** PO intake wizard — steps and reference lists (from system requirements v1.2). */

export {
  formatPoDisplay,
  ASSIGNMENT_TYPE_OPTIONS,
  type AssignmentType,
  ASSIGNMENT_PRIMARY_OPTIONS,
  type AssignmentPrimary,
  type AssignmentSecondary,
  assignmentPrimary,
  assignmentSecondary,
  assignmentCompositeTag,
  secondaryOptionsForPrimary,
  assignmentTypeFromParts,
  showsValuationReportUserField,
  isInfathClient,
  isNabrClient,
  isSelectableWorkOrderClient,
  INFATH_SUB_CLIENT_IDS,
  showsSubClientField,
  defaultSubClientId,
  subClientIdFromReportUsers,
  VALUATION_REPORT_USER_OPTION_LABEL,
  reportUserClientIdsForAssignment,
  VALUATION_PURPOSE_AUCTION_LIQUIDATION,
  VALUATION_PURPOSE_SALE,
  VALUE_BASIS_MARKET,
  VALUE_BASIS_LIQUIDATION,
  valuationPurposeForAssignment,
  basisOfValueForAssignment,
  valuePremiseForAssignment,
  isCourtAssignmentPath,
  requiresAssignmentDecree,
  showsCourtFields,
  requiresRequestNumberField,
  requiresContacts,
  businessDaysForAssignmentType,
  COURTS_BY_CITY,
} from "./po-intake-assignment";

export {
  DEED_STATUS_OPTIONS,
  type BourseDeedVitality,
  BOURSE_DEED_VITALITY_ACTIVE,
  BOURSE_DEED_VITALITY_INACTIVE,
  BOURSE_OBSTRUCTION_LABEL,
  RESTRICTIONS_PRESENT_OPTIONS,
  RESTRICTION_TYPE_OPTIONS,
  type RestrictionTypeValue,
  parseRestrictionTypes,
  joinRestrictionTypes,
  hasRestrictionType,
  toggleRestrictionType,
  BOUNDARIES_AVAILABILITY_OPTIONS,
  classificationRequiresSurvey,
  propertyHasRegisteredTitle,
  propertyRequiresSurvey,
  type PropertyIdentifierType,
  BOURSE_INQUIRY_IDENTIFIER_STATUS,
  isBourseInquiryIdentifier,
  skipsBourseForIdentifier,
  propertySkipsBourse,
  parsePropertyIdentifierType,
  identifierTypeLabel,
  formatPropertyDeedDisplay,
  formatPendingBourseDeedDisplay,
  PROPERTY_IDENTIFIER_MAX_LENGTH,
  DEED_NUMBER_DIGIT_LENGTH,
  REAL_ESTATE_REG_NUMBER_DIGIT_LENGTH,
  requiredPropertyIdentifierDigitLength,
  propertyIdentifierFieldLabel,
  PROPERTY_IDENTIFIER_COLUMN_LABEL,
  sanitizePropertyIdentifierInput,
  normalizePropertyIdentifierNumber,
  validatePropertyIdentifierNumber,
  restrictionsPresentLabel,
  formatPropertyRestrictionsLine,
  boundariesAvailabilityLabel,
  boundariesDetailFieldsOptional,
  boundariesMarkedUnavailable,
} from "./po-intake-identifiers";

export {
  PROPERTY_BOUNDARY_ROWS,
  PROPERTY_BOUNDARY_TYPE_OPTIONS,
  PROPERTY_FINISHING_TYPE_OPTIONS,
  PROPERTY_FINISHING_STRUCTURE_OPTIONS,
  type PropertyBoundaryDescKey,
  type PropertyBoundaryLenKey,
  type PropertyBoundaryTypeKey,
  type PropertyBoundaryFacadeKey,
  clearPropertyBoundaryFields,
  approximatePropertyMapSearchUrl,
  approximatePropertyGeo,
  formatGeoDms,
  formatGeoDec,
  buildPropertyDescriptionLine,
} from "./po-intake-boundaries";

export {
  INCOMPLETE_CONTACT_MARKER_PHONE,
  CONTACT_ROLE_OPTIONS,
  contactRoleSelectOptions,
  type PoContact,
  type PropertyUiStatus,
  propertyUiStatusLabel,
  propertyUiStatusTone,
  ownershipStatusLabel,
  hasBourseDetailFields,
  formatPropertyLocation,
  formatPropertyTypeLine,
  type PoPropertyIntake,
  type PoIntakeRecord,
  emptyProperty,
} from "./po-intake-property-model";

export {
  isBusinessDay,
  getEffectiveStartDate,
  computeBusinessDueDate,
  dueDateToDeadline,
  isPastDue,
} from "./po-intake-due-dates";

/** DD/MM/YYYY with Western digits (0-9) for Arabic UI — moved to the shared package. */
export { formatDateAr } from "@platform/app-shared/format/date";
