using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RealEstateEval.Infrastructure.Data.Contexts;

#nullable disable

namespace RealEstateEval.Infrastructure.Data.Contexts.Identity.Migrations;

/// <summary>
/// Empty identity baseline assumed the shared database already had ASP.NET Identity tables.
/// A dedicated identity database has no legacy stream, so this creates the baseline tables
/// when they are missing.
/// </summary>
[DbContext(typeof(IdentityDbContext))]
[Migration("20260730070118_EnsureIdentityTablesForStandalone")]
public class EnsureIdentityTablesForStandalone : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE SCHEMA IF NOT EXISTS identity;

            CREATE TABLE IF NOT EXISTS identity."Roles"
            (
                "Id" text NOT NULL,
                "Name" character varying(256) NULL,
                "NormalizedName" character varying(256) NULL,
                "ConcurrencyStamp" text NULL,
                CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex"
                ON identity."Roles" ("NormalizedName");

            CREATE TABLE IF NOT EXISTS identity."Users"
            (
                "Id" text NOT NULL,
                "UserName" character varying(256) NULL,
                "NormalizedUserName" character varying(256) NULL,
                "Email" character varying(256) NULL,
                "NormalizedEmail" character varying(256) NULL,
                "EmailConfirmed" boolean NOT NULL,
                "PasswordHash" text NULL,
                "SecurityStamp" text NULL,
                "ConcurrencyStamp" text NULL,
                "PhoneNumber" text NULL,
                "PhoneNumberConfirmed" boolean NOT NULL,
                "TwoFactorEnabled" boolean NOT NULL,
                "LockoutEnd" timestamp with time zone NULL,
                "LockoutEnabled" boolean NOT NULL,
                "AccessFailedCount" integer NOT NULL,
                "DisplayName" text NOT NULL,
                CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
            );
            CREATE INDEX IF NOT EXISTS "EmailIndex" ON identity."Users" ("NormalizedEmail");
            CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON identity."Users" ("NormalizedUserName");

            CREATE TABLE IF NOT EXISTS identity."RoleClaims"
            (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "RoleId" text NOT NULL,
                "ClaimType" text NULL,
                "ClaimValue" text NULL,
                CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id")
            );
            CREATE INDEX IF NOT EXISTS "IX_RoleClaims_RoleId" ON identity."RoleClaims" ("RoleId");

            CREATE TABLE IF NOT EXISTS identity."UserClaims"
            (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "UserId" text NOT NULL,
                "ClaimType" text NULL,
                "ClaimValue" text NULL,
                CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id")
            );
            CREATE INDEX IF NOT EXISTS "IX_UserClaims_UserId" ON identity."UserClaims" ("UserId");

            CREATE TABLE IF NOT EXISTS identity."UserLogins"
            (
                "LoginProvider" text NOT NULL,
                "ProviderKey" text NOT NULL,
                "ProviderDisplayName" text NULL,
                "UserId" text NOT NULL,
                CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey")
            );
            CREATE INDEX IF NOT EXISTS "IX_UserLogins_UserId" ON identity."UserLogins" ("UserId");

            CREATE TABLE IF NOT EXISTS identity."UserRoles"
            (
                "UserId" text NOT NULL,
                "RoleId" text NOT NULL,
                CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId")
            );
            CREATE INDEX IF NOT EXISTS "IX_UserRoles_RoleId" ON identity."UserRoles" ("RoleId");

            CREATE TABLE IF NOT EXISTS identity."UserTokens"
            (
                "UserId" text NOT NULL,
                "LoginProvider" text NOT NULL,
                "Name" text NOT NULL,
                "Value" text NULL,
                CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name")
            );

            CREATE TABLE IF NOT EXISTS identity."UserProfiles"
            (
                "UserId" text NOT NULL,
                "ContractType" integer NOT NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                "DistributionAssigneeId" character varying(128) NULL,
                "JobTitle" character varying(256) NOT NULL,
                "PermissionLevel" character varying(64) NULL,
                "RegistrationSource" integer NOT NULL,
                "ReviewerCityCoverageJson" character varying(1024) NULL,
                "Status" integer NOT NULL,
                CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("UserId")
            );
            CREATE INDEX IF NOT EXISTS "IX_UserProfiles_DistributionAssigneeId"
                ON identity."UserProfiles" ("DistributionAssigneeId");

            CREATE TABLE IF NOT EXISTS identity."HrEmployeeProfiles"
            (
                "UserId" text NOT NULL,
                "Department" character varying(256) NOT NULL,
                "EmployeeNumber" text NULL,
                "EmploymentType" character varying(64) NOT NULL,
                "JoinDate" date NULL,
                "NationalId" text NULL,
                "Section" character varying(256) NULL,
                CONSTRAINT "PK_HrEmployeeProfiles" PRIMARY KEY ("UserId")
            );

            CREATE TABLE IF NOT EXISTS identity."ProcServiceProviderProfiles"
            (
                "UserId" text NOT NULL,
                "Address" text NULL,
                "BankName" text NULL,
                "BillingEmail" text NULL,
                "CommercialRegistration" text NULL,
                "DelegateName" text NULL,
                "FullName" text NULL,
                "Iban" text NULL,
                "NationalId" text NULL,
                "OrganizationName" text NULL,
                "ProviderKind" integer NOT NULL,
                "Region" text NULL,
                "Sector" text NULL,
                "ServiceType" character varying(128) NOT NULL,
                "VatRegistration" text NULL,
                CONSTRAINT "PK_ProcServiceProviderProfiles" PRIMARY KEY ("UserId")
            );

            CREATE TABLE IF NOT EXISTS identity."RefreshTokens"
            (
                "Id" uuid NOT NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL,
                "ExpiresAtUtc" timestamp with time zone NOT NULL,
                "RevokedAtUtc" timestamp with time zone NULL,
                "RevokedReason" character varying(128) NULL,
                "SessionId" uuid NOT NULL,
                "TokenHash" character varying(64) NOT NULL,
                "UserId" character varying(450) NOT NULL,
                CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id")
            );
            CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_ExpiresAtUtc" ON identity."RefreshTokens" ("ExpiresAtUtc");
            CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_SessionId" ON identity."RefreshTokens" ("SessionId");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_RefreshTokens_TokenHash" ON identity."RefreshTokens" ("TokenHash");
            CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_UserId" ON identity."RefreshTokens" ("UserId");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
    }
}
