using System.Text;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using RealEstateEval.Application.Contracts;
using RealEstateEval.Attachments.Application.Abstractions;
using RealEstateEval.CaseStudy.Domain;
using RealEstateEval.CaseStudy.Infrastructure.Persistence;
using RealEstateEval.Domain;
using RealEstateEval.Infrastructure.Services;
using RealEstateEval.Valuation.Application.Abstractions;
using RealEstateEval.Valuation.Application.Contracts;
using RealEstateEval.Valuation.Application.Rules;
using RealEstateEval.Valuation.Domain;
using RealEstateEval.Valuation.Infrastructure.Integration;
using RealEstateEval.Valuation.Infrastructure.Services;

namespace RealEstateEval.Application.Tests;

/// <summary>
/// The final report: the approved report (frozen at approval) with the recorded deposit code in each page header and the
/// certificate page appended, generated by the server, stored in the attachments service next to the certificate, and
/// regenerated when the code is corrected. A renderer failure never undoes the code registration.
/// </summary>
public class ValuationFinalReportTests
{
    private const string AppraiserDistributionId = "val-abdullah";

    private static readonly ReportDraftActor Specialist = new() { UserId = "u-spec", PrototypeRole = "case-specialist" };
    private static readonly ReportDraftActor Supervisor = new() { UserId = "u-sup", PrototypeRole = "section-supervisor" };
    private static readonly ReportDraftActor Stranger = new() { UserId = "u-fi", PrototypeRole = "field-inspector" };
    private static readonly ReportDraftActor Appraiser = new()
    {
        UserId = "u-app", PrototypeRole = "real-estate-appraiser", DistributionAssigneeId = AppraiserDistributionId,
    };

    private const string ApprovedHtml =
        "<html><body>"
        + "<div class=\"pg-meta\">رقم التقرير: 047789<br>التاريخ: 2026/10/05<br>رمز إيداع التقرير:</div><p>p1</p>"
        + "<div class=\"pg-meta\">رقم التقرير: 047789<br>التاريخ: 2026/10/05<br>رمز إيداع التقرير: —</div><p>p2</p>"
        + "<div class=\"other\">رمز إيداع التقرير: keep</div>"
        + "</body></html>";

    // ---- the code line rewrite ----

    [Fact]
    public void The_code_is_written_into_every_page_header_and_nowhere_else()
    {
        var result = ReportDepositCodeRewriter.Apply(ApprovedHtml, "QYM-77");

        Assert.Equal(2, result.Replaced);
        Assert.Equal(2, CountOf(result.Html, "رمز إيداع التقرير: QYM-77</div>"));
        Assert.Contains("<div class=\"other\">رمز إيداع التقرير: keep</div>", result.Html);
        Assert.Contains("<p>p1</p>", result.Html);
        Assert.Contains("رقم التقرير: 047789<br>التاريخ: 2026/10/05<br>", result.Html);
    }

    [Fact]
    public void The_code_is_html_encoded_and_a_page_without_the_line_is_left_alone()
    {
        var encoded = ReportDepositCodeRewriter.Apply(ApprovedHtml, "A<b>&1");
        Assert.Contains("رمز إيداع التقرير: A&lt;b&gt;&amp;1</div>", encoded.Html);

        var none = ReportDepositCodeRewriter.Apply("<div class=\"pg-meta\">رقم التقرير: 1</div>", "X");
        Assert.Equal(0, none.Replaced);
    }

    // ---- the certificate goes to the attachments service ----

    [Fact]
    public async Task The_certificate_is_stored_in_the_attachments_service_and_the_copy_keeps_the_reference()
    {
        await using var rig = await ArrangeApprovedAsync();

        var (state, errors) = await rig.Service.RecordDepositAsync(rig.RequestId, Certificate("QYM-1"), Appraiser);
        Assert.Null(errors);
        Assert.Equal(ReportIssuanceStages.FinalIssued, state!.Stage);

        var stored = Assert.Single(rig.Files.Stored, f => f.Scope == ReportFileScopes.DepositCertificate);
        Assert.Equal($"{rig.PropertyId:D}:deposit:v1", stored.ScopeKey);
        Assert.Equal(TestPdf.OnePage, stored.Content);

        var row = await rig.Contexts.Valuation.ValuationReportIssuances.AsNoTracking().SingleAsync();
        Assert.Equal(stored.Id, row.CertificateAttachmentId);
        Assert.Null(row.CertificateContent);
        Assert.True(row.HasCertificate);
    }

    [Fact]
    public async Task A_failing_store_refuses_the_registration_and_records_nothing()
    {
        await using var rig = await ArrangeApprovedAsync();
        rig.Files.FailWith = "تعذّر حفظ الملف في خدمة المرفقات";

        var (_, errors) = await rig.Service.RecordDepositAsync(rig.RequestId, Certificate("QYM-1"), Appraiser);

        Assert.Equal("تعذّر حفظ الملف في خدمة المرفقات", errors!["certificateContentBase64"]);
        var row = await rig.Contexts.Valuation.ValuationReportIssuances.AsNoTracking().SingleAsync();
        Assert.Null(row.DepositCode);
        Assert.Null(row.FinalIssuedAtUtc);
    }

    [Fact]
    public async Task A_replacement_certificate_removes_the_one_it_replaced()
    {
        await using var rig = await ArrangeApprovedAsync();
        await rig.Service.RecordDepositAsync(rig.RequestId, Certificate("QYM-1"), Appraiser);
        var first = rig.Files.Stored.Single(f => f.Scope == ReportFileScopes.DepositCertificate).Id;

        var (_, errors) = await rig.Service.RecordDepositAsync(rig.RequestId, Certificate("QYM-1"), Appraiser);

        Assert.Null(errors);
        Assert.Contains(first, rig.Files.Deleted);
        var row = await rig.Contexts.Valuation.ValuationReportIssuances.AsNoTracking().SingleAsync();
        Assert.NotEqual(first, row.CertificateAttachmentId);
    }

    // ---- the final PDF ----

    [Fact]
    public async Task The_final_pdf_is_the_approved_report_with_the_code_plus_the_certificate_page()
    {
        await using var rig = await ArrangeApprovedAsync();

        var (state, errors) = await rig.Service.RecordDepositAsync(rig.RequestId, Certificate("QYM-1"), Appraiser);

        Assert.Null(errors);
        Assert.Equal(FinalReportStatuses.Ready, state!.FinalReportStatus);

        // The renderer got the approved HTML with the code in both headers.
        var html = Assert.Single(rig.Renderer.Rendered);
        Assert.Equal(2, CountOf(html, "رمز إيداع التقرير: QYM-1</div>"));

        // The merge joined the rendered report and the certificate, in that order.
        var merged = Assert.Single(rig.Merger.Merges);
        Assert.Equal(2, merged.Count);
        Assert.Equal(FakeRenderer.Pdf, merged[0]);
        Assert.Equal(TestPdf.OnePage, merged[1]);

        var final = Assert.Single(rig.Files.Stored, f => f.Scope == ReportFileScopes.FinalReport);
        Assert.Equal($"{rig.PropertyId:D}:final:v1", final.ScopeKey);
        Assert.Equal(FakeMerger.Merged, final.Content);

        var row = await rig.Contexts.Valuation.ValuationReportIssuances.AsNoTracking().SingleAsync();
        Assert.Equal(final.Id, row.FinalPdfAttachmentId);
        Assert.Equal("QYM-1", row.FinalPdfDepositCode);
        Assert.True(row.FinalPdfIsCurrent);
    }

    [Fact]
    public async Task A_current_final_pdf_is_not_generated_again()
    {
        await using var rig = await ArrangeApprovedAsync();
        await rig.Service.RecordDepositAsync(rig.RequestId, Certificate("QYM-1"), Appraiser);

        var status = await rig.FinalReports.EnsureGeneratedAsync(rig.RequestId);

        Assert.Equal(FinalReportStatuses.Ready, status);
        Assert.Single(rig.Renderer.Rendered);
    }

    [Fact]
    public async Task A_code_correction_regenerates_the_pdf_and_removes_the_stale_one()
    {
        await using var rig = await ArrangeApprovedAsync();
        await rig.Service.RecordDepositAsync(rig.RequestId, Certificate("QYM-1"), Appraiser);
        var stale = rig.Files.Stored.Single(f => f.Scope == ReportFileScopes.FinalReport).Id;

        var (state, errors) = await rig.Service.RecordDepositAsync(
            rig.RequestId, new RegisterDepositCertificateRequest { DepositCode = "QYM-2" }, Appraiser);

        Assert.Null(errors);
        Assert.Equal(FinalReportStatuses.Ready, state!.FinalReportStatus);
        Assert.Equal(2, rig.Renderer.Rendered.Count);
        Assert.Equal(2, CountOf(rig.Renderer.Rendered[1], "رمز إيداع التقرير: QYM-2</div>"));
        Assert.Contains(stale, rig.Files.Deleted);

        var row = await rig.Contexts.Valuation.ValuationReportIssuances.AsNoTracking().SingleAsync();
        Assert.Equal("QYM-2", row.FinalPdfDepositCode);
        Assert.NotEqual(stale, row.FinalPdfAttachmentId);
    }

    [Fact]
    public async Task A_renderer_failure_keeps_the_code_registered_and_can_be_retried()
    {
        await using var rig = await ArrangeApprovedAsync();
        rig.Renderer.Fail = true;

        var (state, errors) = await rig.Service.RecordDepositAsync(rig.RequestId, Certificate("QYM-1"), Appraiser);

        Assert.Null(errors);
        Assert.Equal(ReportIssuanceStages.FinalIssued, state!.Stage);
        Assert.Equal("QYM-1", state.DepositCode);
        Assert.Equal(FinalReportStatuses.Preparing, state.FinalReportStatus);
        Assert.DoesNotContain(rig.Files.Stored, f => f.Scope == ReportFileScopes.FinalReport);

        rig.Renderer.Fail = false;
        var (status, retryErrors) = await rig.Service.RegenerateFinalReportAsync(rig.RequestId, Specialist);

        Assert.Null(retryErrors);
        Assert.Equal(FinalReportStatuses.Ready, status);
        Assert.Contains(rig.Files.Stored, f => f.Scope == ReportFileScopes.FinalReport);
    }

    [Fact]
    public async Task A_report_without_the_code_line_is_not_turned_into_a_final_pdf()
    {
        await using var rig = await ArrangeApprovedAsync("<html><body><p>no header here</p></body></html>");

        var (state, errors) = await rig.Service.RecordDepositAsync(rig.RequestId, Certificate("QYM-1"), Appraiser);

        Assert.Null(errors);
        Assert.Equal(FinalReportStatuses.Preparing, state!.FinalReportStatus);
        Assert.Empty(rig.Renderer.Rendered);
    }

    [Fact]
    public async Task The_final_report_is_not_prepared_before_the_final_issuance()
    {
        await using var rig = await ArrangeApprovedAsync();

        Assert.Equal(FinalReportStatuses.None, await rig.FinalReports.EnsureGeneratedAsync(rig.RequestId));
        Assert.Null(await rig.FinalReports.GetFileAsync(rig.RequestId));
    }

    // ---- who may download / retry ----

    [Fact]
    public async Task The_specialist_the_management_and_the_assigned_appraiser_download_the_final_report()
    {
        await using var rig = await ArrangeApprovedAsync();
        await rig.Service.RecordDepositAsync(rig.RequestId, Certificate("QYM-1"), Appraiser);

        foreach (var actor in new[] { Specialist, Supervisor, Appraiser })
        {
            var (file, errors) = await rig.Service.GetFinalReportAsync(rig.RequestId, actor);
            Assert.Null(errors);
            Assert.Equal(FakeMerger.Merged, file!.Content);
            Assert.Equal("final-report-v1.pdf", file.FileName);
        }
    }

    [Fact]
    public async Task Another_role_or_another_appraiser_cannot_download_or_retry()
    {
        await using var rig = await ArrangeApprovedAsync();
        await rig.Service.RecordDepositAsync(rig.RequestId, Certificate("QYM-1"), Appraiser);
        var otherAppraiser = new ReportDraftActor
        {
            UserId = "u-app2", PrototypeRole = "real-estate-appraiser", DistributionAssigneeId = "val-someone-else",
        };

        foreach (var actor in new[] { Stranger, otherAppraiser })
        {
            var (file, errors) = await rig.Service.GetFinalReportAsync(rig.RequestId, actor);
            Assert.Null(file);
            Assert.Equal(ValuationReportDraftService.FinalReportForbiddenAr, errors![ReportDraftErrorKeys.Forbidden]);

            var (status, retryErrors) = await rig.Service.RegenerateFinalReportAsync(rig.RequestId, actor);
            Assert.Null(status);
            Assert.True(retryErrors!.ContainsKey(ReportDraftErrorKeys.Forbidden));
        }
    }

    [Fact]
    public async Task A_download_before_the_pdf_exists_says_it_is_being_prepared()
    {
        await using var rig = await ArrangeApprovedAsync();
        rig.Renderer.Fail = true;
        await rig.Service.RecordDepositAsync(rig.RequestId, Certificate("QYM-1"), Appraiser);

        var (file, errors) = await rig.Service.GetFinalReportAsync(rig.RequestId, Specialist);

        Assert.Null(file);
        Assert.Equal(ValuationReportDraftService.FinalReportNotReadyAr, errors!["_"]);
    }

    // ---- the batch states the queues read ----

    [Fact]
    public async Task The_batch_states_report_the_draft_and_the_report_stage_per_property()
    {
        await using var rig = await ArrangeApprovedAsync();
        var other = Guid.NewGuid();

        var approved = await rig.Service.ListStatesAsync([rig.PropertyId, other]);
        var one = Assert.Single(approved);
        Assert.Equal(rig.PropertyId, one.PropertyId);
        Assert.Equal(ReportDraftStatuses.Approved, one.Status);
        Assert.Equal(ReportIssuanceStages.DepositIssued, one.ReportStage);
        Assert.Equal(AppraiserProgressRules.Approved, one.ProgressPct);

        await rig.Service.RecordDepositAsync(rig.RequestId, Certificate("QYM-1"), Appraiser);
        var final = Assert.Single(await rig.Service.ListStatesAsync([rig.PropertyId]));
        Assert.Equal(ReportIssuanceStages.FinalIssued, final.ReportStage);
        Assert.Equal(AppraiserProgressRules.FinalIssued, final.ProgressPct);
    }

    [Fact]
    public async Task The_batch_states_of_nothing_are_empty()
    {
        await using var rig = Arrange();
        Assert.Empty(await rig.Service.ListStatesAsync([]));
    }

    // ---- arrangement ----

    private static int CountOf(string text, string needle)
    {
        var count = 0;
        for (var i = text.IndexOf(needle, StringComparison.Ordinal); i >= 0; i = text.IndexOf(needle, i + needle.Length, StringComparison.Ordinal))
            count++;
        return count;
    }

    private static RegisterDepositCertificateRequest Certificate(string code) => new()
    {
        DepositCode = code,
        CertificateFileName = "certificate.pdf",
        CertificateContentType = "application/pdf",
        CertificateContentBase64 = TestPdf.OnePageBase64,
    };

    private static async Task<Rig> ArrangeApprovedAsync(string html = ApprovedHtml)
    {
        var rig = Arrange();
        var choices = System.Text.Json.JsonDocument.Parse("{}").RootElement.Clone();
        await rig.Service.SaveChoicesAsync(rig.RequestId, new SaveReportDraftChoicesRequest { Choices = choices }, Specialist);
        await rig.Service.SendAsync(rig.RequestId, new SendReportDraftRequest { ConformityConfirmed = true }, Specialist);
        var (_, errors) = await rig.Service.ApproveAsync(
            rig.RequestId, new ApproveReportDraftRequest { ReportDate = "2026-10-05", Html = html }, Appraiser);
        Assert.Null(errors);
        return rig;
    }

    private static Rig Arrange()
    {
        var contexts = TestDatabases.Create("final-report");
        var propertyId = Guid.NewGuid();
        var requestId = Guid.NewGuid();
        contexts.Valuation.ValuationRequests.Add(ValuationRequest.Create(
            requestId, "VR-F1", propertyId, "جدة", "فيلا", "مقيم", "2026-06-25", DateTime.UtcNow));
        contexts.Valuation.SaveChanges();

        var taskId = Guid.NewGuid();
        contexts.CaseStudy.WorkflowTasks.Add(WorkflowTask.Create(
            WorkflowTaskKind.PropertyAppraisal, "PO-F", DateTime.UtcNow, title: "تقييم",
            phase: WorkflowTaskPhase.Done, id: taskId, propertyId: propertyId, assigneeId: AppraiserDistributionId));
        var package = PartyTaskSubmission.CreateDraft(
            taskId, WorkflowTaskKindValues.PropertyAppraisal, propertyId, "PO-F", DateTime.UtcNow);
        package.Status = PartyTaskSubmissionStatus.Submitted;
        contexts.CaseStudy.PartyTaskSubmissions.Add(package);
        contexts.CaseStudy.SaveChanges();

        var clock = new FixedClock(new DateTimeOffset(2026, 10, 5, 9, 0, 0, TimeSpan.Zero));
        var lookup = new CaseStudyLookup(contexts.CaseStudy);
        var events = new ValuationOutboxPublisher(contexts.Valuation, NullLogger<ValuationOutboxPublisher>.Instance);
        var files = new FakeFileStore();
        var issuance = new ValuationReportIssuanceService(
            contexts.Valuation,
            new StubGates(),
            new StubDocuments(),
            time: clock,
            audit: new AuditLogWriter(),
            auditLog: new RecordingAuditLogAppend(),
            events: events,
            caseStudy: lookup,
            files: files);
        var renderer = new FakeRenderer();
        var merger = new FakeMerger();
        var finalReports = new ValuationFinalReportService(contexts.Valuation, renderer, merger, files, clock);
        var service = new ValuationReportDraftService(contexts.Valuation, issuance, lookup, events, clock, finalReports);
        return new Rig(contexts, requestId, propertyId, service, finalReports, files, renderer, merger);
    }

    private sealed class FixedClock(DateTimeOffset now) : TimeProvider
    {
        public override DateTimeOffset GetUtcNow() => now;
    }

    private sealed class Rig(
        TestDatabases.ContextSet contexts,
        Guid requestId,
        Guid propertyId,
        ValuationReportDraftService service,
        ValuationFinalReportService finalReports,
        FakeFileStore files,
        FakeRenderer renderer,
        FakeMerger merger) : IAsyncDisposable
    {
        public TestDatabases.ContextSet Contexts { get; } = contexts;
        public Guid RequestId { get; } = requestId;
        public Guid PropertyId { get; } = propertyId;
        public ValuationReportDraftService Service { get; } = service;
        public ValuationFinalReportService FinalReports { get; } = finalReports;
        public FakeFileStore Files { get; } = files;
        public FakeRenderer Renderer { get; } = renderer;
        public FakeMerger Merger { get; } = merger;
        public ValueTask DisposeAsync() => Contexts.DisposeAsync();
    }

    private sealed record StoredFile(Guid Id, string Scope, string ScopeKey, string FileName, byte[] Content);

    private sealed class FakeFileStore : IAttachmentFileStore
    {
        public List<StoredFile> Stored { get; } = [];
        public List<Guid> Deleted { get; } = [];
        public string? FailWith { get; set; }

        public Task<(Guid? Id, string? Error)> StoreAsync(
            string scope, string scopeKey, string fileName, string contentType, byte[] content,
            CancellationToken cancellationToken = default)
        {
            if (FailWith is not null) return Task.FromResult<(Guid?, string?)>((null, FailWith));
            var id = Guid.NewGuid();
            Stored.Add(new StoredFile(id, scope, scopeKey, fileName, content));
            return Task.FromResult<(Guid?, string?)>((id, null));
        }

        public Task<byte[]?> ReadAsync(Guid id, CancellationToken cancellationToken = default) =>
            Task.FromResult(Stored.FirstOrDefault(f => f.Id == id && !Deleted.Contains(id))?.Content);

        public Task DeleteAsync(Guid id, CancellationToken cancellationToken = default)
        {
            Deleted.Add(id);
            return Task.CompletedTask;
        }
    }

    private sealed class FakeRenderer : IHtmlPdfRenderer
    {
        public static readonly byte[] Pdf = Encoding.ASCII.GetBytes("%PDF-1.4 rendered report");
        public List<string> Rendered { get; } = [];
        public bool Fail { get; set; }
        public string Name => "fake";
        public bool IsConfigured => true;

        public Task<byte[]> RenderAsync(string html, CancellationToken cancellationToken = default)
        {
            if (Fail) throw new HtmlPdfRendererUnavailableException("renderer is down");
            Rendered.Add(html);
            return Task.FromResult(Pdf);
        }
    }

    private sealed class FakeMerger : IPdfMerger
    {
        public static readonly byte[] Merged = Encoding.ASCII.GetBytes("%PDF-1.4 merged");
        public List<IReadOnlyList<byte[]>> Merges { get; } = [];

        public Task<byte[]> MergeAsync(IReadOnlyList<byte[]> pdfs, CancellationToken cancellationToken = default)
        {
            Merges.Add(pdfs);
            return Task.FromResult(Merged);
        }
    }

    private sealed class StubGates : IValuationIssuanceGateService
    {
        public Task<ValuationIssuanceGatesDto?> EvaluateAsync(
            Guid valuationRequestId, CancellationToken cancellationToken = default) =>
            Task.FromResult<ValuationIssuanceGatesDto?>(new ValuationIssuanceGatesDto
            {
                ValuationRequestId = valuationRequestId, AllowsIssuance = true, BlockingReasonsAr = [],
            });
    }

    private sealed class StubDocuments : IValuationReportDocumentService
    {
        public Task<ValuationReportDocumentDto?> GetPreviewAsync(
            Guid valuationRequestId, CancellationToken cancellationToken = default) =>
            Task.FromResult<ValuationReportDocumentDto?>(new ValuationReportDocumentDto
            {
                ValuationRequestId = valuationRequestId,
                DisplayId = "VR-TEST",
                ReportDateDisplay = "2026/10/05",
                FinalOpinionDisplay = "1,000,000 ريال",
                Sections = [],
            });
    }
}
