"use client";

/**
 * All non-rendering workflow behind `OperationsTasksView`, composed from its
 * halves: reads in `useOperationsTasksData` (queries, queue filters, selection
 * and detail), writes in `useOperationsTasksCommands` (status, close, pause,
 * comments, reminders, failure raise) and
 * `useOperationsTasksAssignmentCommands` (priority, reassign). This file only
 * wires them and builds the row menu; the view consumes the returned bag and
 * keeps JSX plus event wiring only.
 */
import { useCallback } from "react";
import type { RowMoreMenuItem } from "@platform/ui-kit";
import type { OperationsTask } from "../lib/app-data/operations-tasks-model";
import { buildOperationsTaskRowMenu } from "./operations-tasks-view-state";
import { useOperationsTasksData } from "./useOperationsTasksData";
import { useOperationsTasksCommands } from "./useOperationsTasksCommands";
import { useOperationsTasksAssignmentCommands } from "./useOperationsTasksAssignmentCommands";

export function useOperationsTasksWorkflow() {
  const data = useOperationsTasksData();
  const commands = useOperationsTasksCommands(data);
  const assignment = useOperationsTasksAssignmentCommands({ data, commands });
  const { canCreate, canRemind, reviewerAccount, setDetailId } = data;
  const {
    runStatus,
    remindTask,
    openCloseModal,
    openKeysRegisterFromTask,
    openPauseModal,
  } = commands;
  const { openPriorityModal, openReassign } = assignment;

  const rowMenu = useCallback(
    (task: OperationsTask): RowMoreMenuItem[] =>
      buildOperationsTaskRowMenu(
        task,
        { canCreate, canRemind, reviewerAccount },
        {
          showDetail: (t) => setDetailId(t.id),
          markInProgress: (t) => void runStatus(t.id, "in_progress"),
          closeTask: openCloseModal,
          registerEnvelope: openKeysRegisterFromTask,
          pauseTask: openPauseModal,
          remindTask: (t) => void remindTask(t),
          changePriority: openPriorityModal,
          reassignTask: openReassign,
        },
      ),
    [
      canCreate,
      canRemind,
      reviewerAccount,
      setDetailId,
      runStatus,
      remindTask,
      openReassign,
      openCloseModal,
      openPriorityModal,
      openKeysRegisterFromTask,
      openPauseModal,
    ],
  );

  return {
    afterGovFailureRaised: commands.afterGovFailureRaised,
    allVisibleActiveChecked: data.allVisibleActiveChecked,
    applyPrioDueFromOffset: assignment.applyPrioDueFromOffset,
    applyPriority: assignment.applyPriority,
    bulkRemind: commands.bulkRemind,
    bulkReminding: commands.bulkReminding,
    busy: commands.busy,
    canCreate,
    canRemind,
    cancelReason: commands.cancelReason,
    closeFileInputRef: commands.closeFileInputRef,
    closeFiles: commands.closeFiles,
    closeFormError: commands.closeFormError,
    closeOpen: commands.closeOpen,
    closeOutcome: commands.closeOutcome,
    closeText: commands.closeText,
    commentFileInputRef: commands.commentFileInputRef,
    commentFiles: commands.commentFiles,
    commentText: commands.commentText,
    confirmCloseTask: commands.confirmCloseTask,
    confirmPauseTask: commands.confirmPauseTask,
    courtContacts: commands.courtContacts,
    courtKind: commands.courtKind,
    courtOtherText: commands.courtOtherText,
    courtPerDeed: commands.courtPerDeed,
    courtStatement: commands.courtStatement,
    createOpen: data.createOpen,
    createPrefill: data.createPrefill,
    creditAssigneeId: commands.creditAssigneeId,
    creditAssignees: data.creditAssignees,
    detail: data.detail,
    error: commands.error,
    govFailureTarget: commands.govFailureTarget,
    isAssignee: data.isAssignee,
    isDesktopViewport: data.isDesktopViewport,
    isFetched: data.isFetched,
    isFetching: data.isFetching,
    kpis: data.kpis,
    now: data.now,
    openCloseModal,
    openGovFailureRaise: commands.openGovFailureRaise,
    openKeysRegisterFromTask,
    openPauseModal,
    openPriorityModal,
    openReassign,
    openTask: data.openTask,
    openTaskDetail: data.openTaskDetail,
    pauseError: commands.pauseError,
    pauseOpen: commands.pauseOpen,
    pauseReason: commands.pauseReason,
    poRecords: data.poRecords,
    prioDueDate: assignment.prioDueDate,
    prioDueTime: assignment.prioDueTime,
    prioEditDue: assignment.prioEditDue,
    prioOpen: assignment.prioOpen,
    prioValue: assignment.prioValue,
    reassignAssigneeId: assignment.reassignAssigneeId,
    reassignAssignees: data.reassignAssignees,
    reassignDueDate: assignment.reassignDueDate,
    reassignDueTime: assignment.reassignDueTime,
    reassignError: assignment.reassignError,
    reassignOpen: assignment.reassignOpen,
    reassignReason: assignment.reassignReason,
    reassignTask: data.reassignTask,
    reassigning: assignment.reassigning,
    refetch: data.refetch,
    remindTask,
    reviewerStaff: data.reviewerStaff,
    rowMenu,
    runStatus,
    scopeFilter: data.scopeFilter,
    search: data.search,
    selAllRef: data.selAllRef,
    selectedCount: data.selectedCount,
    selectedId: data.selectedId,
    sendComment: commands.sendComment,
    selectedIds: data.selectedIds,
    setBusy: commands.setBusy,
    setCancelReason: commands.setCancelReason,
    setCloseFiles: commands.setCloseFiles,
    setCloseOpen: commands.setCloseOpen,
    setCloseOutcome: commands.setCloseOutcome,
    setCloseText: commands.setCloseText,
    setCommentFiles: commands.setCommentFiles,
    setCommentText: commands.setCommentText,
    setCourtContacts: commands.setCourtContacts,
    setCourtKind: commands.setCourtKind,
    setCourtOtherText: commands.setCourtOtherText,
    setCourtPerDeed: commands.setCourtPerDeed,
    setCourtStatement: commands.setCourtStatement,
    setCreateOpen: data.setCreateOpen,
    setCreatePrefill: data.setCreatePrefill,
    setCreditAssigneeId: commands.setCreditAssigneeId,
    setCreditAssigneeName: commands.setCreditAssigneeName,
    setDetailId,
    setError: commands.setError,
    setGovFailureTarget: commands.setGovFailureTarget,
    setPauseOpen: commands.setPauseOpen,
    setPauseReason: commands.setPauseReason,
    setPrioDueDate: assignment.setPrioDueDate,
    setPrioDueTime: assignment.setPrioDueTime,
    setPrioEditDue: assignment.setPrioEditDue,
    setPrioOpen: assignment.setPrioOpen,
    setPrioValue: assignment.setPrioValue,
    setReassignAssigneeId: assignment.setReassignAssigneeId,
    setReassignAssigneeName: assignment.setReassignAssigneeName,
    setReassignDueDate: assignment.setReassignDueDate,
    setReassignDueTime: assignment.setReassignDueTime,
    setReassignOpen: assignment.setReassignOpen,
    setReassignReason: assignment.setReassignReason,
    setScopeFilter: data.setScopeFilter,
    setSearch: data.setSearch,
    setSelectedId: data.setSelectedId,
    setSelectedIds: data.setSelectedIds,
    setShowAll: data.setShowAll,
    setStatusFilter: data.setStatusFilter,
    showAll: data.showAll,
    showAllEyeBlink: data.showAllEyeBlink,
    showCreditPicker: data.showCreditPicker,
    showGovFailureRaise: data.showGovFailureRaise,
    staffLoadError: data.staffLoadError,
    staffLoading: data.staffLoading,
    staffUsers: data.staffUsers,
    statusFilter: data.statusFilter,
    submitReassign: assignment.submitReassign,
    tasks: data.tasks,
    toggleShowAll: data.toggleShowAll,
    toggleTaskSelected: data.toggleTaskSelected,
    useIndependentQueue: data.useIndependentQueue,
    visibleTasks: data.visibleTasks,
  };
}
